### ISSUE TITLE
TODO after OHBM Hackathon 2020

### ISSUE THREAD

**Issue by ofgulban** [ofgulban/slowest-particle-simulator-on-earth#3]
- [ ] Upload 3D image with equal dims (experience showed that images thin in one dimension causes confusion in new users)
- [ ] Merge devel-multistage into devel
- [ ] Merge devel into master
- [ ] Bump version
- [ ] Release
- [ ] Update pypi after requirement version updates.
- [ ] Create gallery
